services:
  client:
    build:
      context: .
    image: r-iod
    container_name: riod-client
    ports:
      - 8081:8081
    environment:
        - MODE=CLIENT
        - STREAMLIT_SERVER_PORT=8081
        - LITESTAR_CONTAINER_NAME=riod-server
    networks:
      - riod-network
    
  server:
    build:
        context: .
    image: r-iod
    container_name: riod-server
    ports:
      - 8080:8080
    environment:
        - MODE=SERVER
        - LITESTAR_HOST=0.0.0.0
        - LITESTAR_PORT=8080
    networks:
      - riod-network

networks:
  riod-network:
    name: riod-network
    driver: bridge
